language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
env:
  - CI=false
before_script:
  - cd argo-scholar
script:
  - npm install
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: argo-scholar/build
  on:
    branch: master